feat: add an option to make the path `shortened`
ghillb/cybu.nvim pull request #11
Opened 2022-09-20 22:29 UTC by B4mbus

Added an option to make the path shortened.
![image](https://user-images.githubusercontent.com/75364377/191376069-72a54681-f770-4058-aa44-748cfa082f61.png)

2022-09-21 09:19 UTC, ghillb commented
Hey, this looks cool, and I'm inclined to merge it with some minor changes. Are you OK with implementing some suggestions, I make, and we merge it then?

2022-09-21 09:21 UTC, B4mbus commented
Ofc! Glad you like it.

2022-09-21 10:08 UTC, ghillb commented
Great! I would like to synchronize the looks with the `shorten` option of [telescope](https://github.com/nvim-telescope/telescope.nvim/blob/c92f86386f8446e4deaa79941baabaf825683be9/lua/telescope/config.lua#L302).
Here are pics for comparison:
![telescope](https://user-images.githubusercontent.com/35503959/191467584-0bca375c-4449-41c7-8f76-434e537f6402.png)
![cybu](https://user-images.githubusercontent.com/35503959/191467606-23e31ae6-134f-4c96-af8a-65ccf670571e.png)

Notable differences, telescope (upper image) only uses the relative paths, when `shorten` is set, adds the first char after an `.` for a dot directory and per default the `/` separator is displayed on Linux.

To keep the combination absolute + shorten, one could implement the shorten functionality under a new option key, e.g., `style = { shorten_path = true/false }` or  `style = { path_abbreviation = 'shorten'/'default' }`, to make it easier to implement another abbreviation variant (like telescope's `'smart'`) in the future.

I think the last one is a bug, `vim.fn.has('win32')` returns "0" on Linux, which is truthy in Lua.

2022-09-21 10:09 UTC, ghillb requested changes

2022-09-21 10:09 UTC, ghillb commented on lua/cybu/init.lua
> +      local normalized_name = vim.fn.fnamemodify(name, ':p'):gsub(alternate_separator, preffered_separator)
Could you explain why this has to be done this way (alternate_separator / preffered_separator)?

2022-09-21 10:09 UTC, ghillb commented on lua/cybu/init.lua
> +local function get_preffered_path_separator()
`preffered` -> `preferred`.

2022-09-21 10:09 UTC, ghillb commented on lua/cybu/init.lua
> +local function get_preffered_path_separator()
I think `utils.lua` is a better place for all the new functions.

2022-09-21 10:15 UTC, ghillb commented on lua/cybu/init.lua
> +local function get_alternate_separator(sep)
Maybe the plenary path lib is more robust for this kind of stuff, but that's just a consideration:

https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/path.lua

https://github.com/nvim-telescope/telescope.nvim/blob/6bddc38c25af7b50f99cb0c035248d7272971810/lua/telescope/utils.lua#L19

https://github.com/nvim-telescope/telescope.nvim/blob/6bddc38c25af7b50f99cb0c035248d7272971810/lua/telescope/utils.lua#L254

2022-09-26 10:33 UTC, B4mbus commented
It'd be lovely if you could try that PR locally because I'm not in a position right now to try it on linux, but I believe it should work no problem.

2022-09-26 10:59 UTC, ghillb commented
Yes, I will do it soon.

Regarding 1: It is probably a minor misunderstanding, what I meant, was to keep the current `style = {path = "relative",            -- absolute, relative, tail}` option and to introduce a new option (e.g.: `style = { path_abbreviation = 'shorten'/'default' }`) for the new functionality.
This yields the possibility to shorten relative AND absolute paths, and chance to introduce new abbreviation options easier in the future without breaking changes and could be probably done in relatively few lines of code.

2022-09-26 11:20 UTC, B4mbus commented
Oh, that actually makes sense. How about instead of `path_abbrievation = 'shorten'/'default'` - `path_abbrievation =   'shorten'/'none'` or even `shorten_path = true/false`?

2022-09-26 11:36 UTC, ghillb commented
`path_abbrevation =   'shorten'/'none'` sounds good to me (in case there will be another abbreviation scheme in the future, this will prevent breaking changes)

2022-09-26 19:20 UTC, ghillb commented
> It'd be lovely if you could try that PR locally because I'm not in a position right now to try it on linux, but I believe it should work no problem.

Yes, it works fine now on Linux, and the improvements you made look good too.

2022-09-27 17:25 UTC, B4mbus commented
It should be good now.

2022-09-27 19:29 UTC, ghillb requested changes
I've made only some minor suggestions for docs and typos. Otherwise, LGTM, and I will merge soon :)

2022-09-27 19:29 UTC, ghillb commented on lua/cybu/config.lua
> +    path_abbrievation = "none",
```suggestion
    path_abbreviation = "none",
```

2022-09-27 19:29 UTC, ghillb commented on lua/cybu/init.lua
> +    if c.opts.style.path_abbrievation == v.style_path_abbrievation.shortened then
```suggestion
    if c.opts.style.path_abbreviation == v.style_path_abbreviation.shortened then
```

2022-09-27 19:29 UTC, ghillb commented on lua/cybu/vars.lua
> +vars.style_path_abbrievation = { shortened = "shortened", none = "none" }
```suggestion
vars.style_path_abbreviation = { shortened = "shortened", none = "none" }
```

2022-09-27 19:37 UTC, B4mbus commented
Fixed it.

But oof, don't mind the commit name, I changed them to `abbreviation`, not `abbrevation`, just a typo in the commit :(.

2022-09-27 19:45 UTC, ghillb reviewed
All good, just missed one (see suggestion)

2022-09-27 19:45 UTC, ghillb commented on lua/cybu/init.lua
> +    if c.opts.style.path_abbreviation == v.style_path_abbrevation.shortened then
```suggestion
    if c.opts.style.path_abbreviation == v.style_path_abbreviation.shortened then
```

2022-09-27 19:50 UTC, B4mbus commented
Oh man! Right. Really sorry, I'm a bit dizzy. Hope it's all good now, thanks for your suggestions.

2022-09-27 19:54 UTC, merged